# Copyright 2019 The Fuchsia Authors. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

obj-$(CONFIG_LIBAVB) += avb_atx_validate.o
